bookanook:
  build: .
  command: bundle exec rails server -p 3000 -b '0.0.0.0'
  volumes:
    - .:/home/code
  ports:
    - "3000:3000"
  links:
    - db

db:
  image: postgres:9.4
  volumes:
    - ./postgres-data/var/log/postgresql:/var/log/postgresql
    - ./postgres-data/var/lib/postgresql/data:/var/lib/postgresql/data
  ports:
    - "5432:5432"